### ISSUE TITLE
Debian package with plugins in UnifiedViews/Plugins repository

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Packages#1]
There should be also Debian package containing DPUs (at least those highly used) in UnifiedViews/Plugins repository, so that they can be easily installed

What do you think? 

Markus, please reassign if someone else is responsible.

**Comment by marcoony** [comment]
@skrchnavy  think about installation of dpu plugins..

**Comment by skrchnavy** [comment]
closed, plugins have new package
