### ISSUE TITLE
The unifiedviews-webapp package version 1.3.0

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Packages#11]
Following this http://wiki.lod2.eu/display/LOD2DOC/Installation+of+a+local+LOD2+stack

```
Download the repository stage package, i.e. the final version is lod2final-repository.deb
    wget http://stack.lod2.eu/deb/lod2testing/lod2final-repository_1.34_all.deb
As root/superuser, Install the downloaded package (dpkg –I <package>)
    dpkg -i lod2final-repository_1.34_all.deb
```
then i get unifiedviews-backend 1.3.1, unifiedviews-core-plugins 1.3.1 but unifiedviews-webapp 1.3.0

**Comment by Jan-Marcek** [comment]
is not out of date? Now, we are using our repository - https://utopia.sk/wiki/display/ODN/Open+Data+Node+v0.10.1 

Currently, unifiedviews in version 1.5.5.

Feel free to reopen if it still remains.
