### ISSUE TITLE
Obsolete DPUs preinstalled

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Packages#4]
https://github.com/UnifiedViews/Packages/tree/master/backend/var/lib/unifiedviews/target/dpu
Contains DPUs which are not in 1.3.0 release. Create dpus from https://github.com/UnifiedViews/Plugins repository.

Also in 1.3.0 there is probable the data.sql script contains invalid DPU data.

I would omit DPU preinstallation in 1.3.0 at all, and the issue is resolved in 1.3.1 (in https://github.com/UnifiedViews/Plugins/blob/UV_Plugins_v1.3.1/plugins.sql) but plugins should probably be distributed in separate package.

**Comment by skrchnavy** [comment]
this is not relevant now.
