### ISSUE TITLE
Config files do not contain predefined values for folder

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Packages#5]
These config files
https://github.com/UnifiedViews/Packages/tree/master/backend/etc/unifiedviews
do not have folders set up - working folder (shared between backend and frontend), lib folder etc. See the example configs:
https://github.com/UnifiedViews/Core/blob/UV_Core_v1.3.1/backend/conf/config.sample.properties
https://github.com/UnifiedViews/Core/blob/UV_Core_v1.3.1/frontend/src/main/webapp/WEB-INF/config.sample.properties

**Comment by skrchnavy** [comment]
to check if this is relevant or not in 1.5.0. If relevant, fix it for 1.5.5

**Comment by marcoony** [comment]
It had been fixed in 1.5.0. 
If it hadn't been fixed It wouldn't have been worked.
