### ISSUE TITLE
The postinst script expects deprecated behavior of UV

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Packages#6]
https://github.com/UnifiedViews/Packages/blob/master/backend/DEBIAN/postinst
there is no ~/.odcs/config.properties file search in UV Core since 1.3.0. The config file for frontend can be specified as -DconfigFileLocation=... java opt the same as for backend. For tomcat, that can be set in
tomcat-home/bin/setenv.sh with CATALINA_OPTS="-DconfigFileLocation=..."
in debian like systems by editining /etc/default/tomcat7 and appending to JAVA_OPTS. Or if you incorpote it in any other way into tomcat environment, it is ok.

**Comment by skrchnavy** [comment]
fix in 1.5.5 expected if relevant.

**Comment by marcoony** [comment]
It had been fixed. Frontend looks to web-inf if there is a config file. If it finds the config file then he it will use it. 
Debian package provides configuration file for frontend.

**Comment by skrchnavy** [comment]
@marcoony is there a commit where it is fixed? What version (1.5.0 or 1.5.5)?

**Comment by marcoony** [comment]
https://github.com/UnifiedViews/Core/commit/532cba28f3127e6f0e4a0224fdceb0dcc61af1b9

**Comment by marcoony** [comment]
https://github.com/UnifiedViews/Packages/blob/master/webapp/src/deb/control/postinst#L42
